config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "siswas#index"
  resources :siswas do
  	collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/siswa.rb
class Siswa < ApplicationRecord

	def self.to_csv(fields = column_names, options = {})
		CSV.generate(options) do |csv|
			csv << fields
			all.each do |siswa|
				csv << siswa.attributes.values_at(*fields)
			end
		end
	end

	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			siswa_hash = row.to_hash
			siswa = find_or_create_by!(nama: siswa_hash['nama'], nisn: siswa_hash['nisn'], no_un: siswa_hash['no_un'])
			# siswa.update_attributes(siswa_hash)
		end
	end

	validates :no_un, presence: true, length: {is: 14}
	validates :nisn, presence: true, length: {is: 10}
	validates :nisn, :nama, :jenis_kelamin, :tempat_lahir, :tanggal_lahir, :sekolah_asal, :nama_ortu, :no_hp, presence: true

	def self.total_laki
		where(jenis_kelamin: 'L').count
	end

	def self.total_perempuan
		where(jenis_kelamin: 'P').count
	end

	def self.total_jenis_kelamin
		total_laki + total_perempuan
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable

   enum level: {member: 0, admin: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	rescue_from ActiveRecord::RecordNotUnique, with: :duplicate_error
	rescue_from I18n::ArgumentError, with: :complete_error

	include Pundit
	rescue_from Pundit::NotAuthorizedError, with: :pundit_error
	before_action :configure_permitted_parameters, if: :devise_controller?

	private

	def complete_error
		flash[:warning] = "Data belum lengkap, harap lengkapi data terlebih dahulu."
		redirect_to root_path
	end 

	def duplicate_error
		flash[:danger] = "Mohon maaf data tidak dapat disimpan terjadi duplikasi data No.UN/NISN, harap cek kembali data yang diinput."
		redirect_to edit_siswa_path(@siswa)
	end

	def pundit_error
		flash[:notice] = 'Tidak memiliki hak akses.'
		redirect_to root_path
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/concerns/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/controllers/siswas_controller.rb
class SiswasController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :show, :edit, :destroy]

	def index
		@siswas = Siswa.all
		respond_to do |format|
			format.html
			format.csv { send_data @siswas.to_csv(['no_un', 'nisn', 'nama', 'jenis_kelamin', 'tempat_lahir', 'tanggal_lahir', 'sekolah_asal', 'nama_ortu', 'no_hp'])}
			format.json { render json: SiswasDatatable.new(view_context) }
		end
	end

	def show
		@user = current_user

		if @siswa = Siswa.find(params[:id])
			respond_to do |format|
				format.html
				format.pdf do
					pdf = SiswaPdf.new(@siswa, @user)
					send_data pdf.render,
								filename: "#{@siswa.nama}",
	          					type: 'application/pdf',
	          					disposition: 'inline'
				end
			end
		else
			redirect_to root_path()
		end
	end

	def new
		@siswa = Siswa.new
	end

	def create
		@siswa = Siswa.new(resource_params)
		if 
			@siswa.save
			flash[:notice] = 'Data Siswa baru atas nama ' +@siswa.nama+ ' berhasil ditambahkan'
			redirect_to siswa_path(@siswa)
		else
			render 'new'
		end

	end


	def edit
		@siswa = Siswa.find(params[:id])
	end

	def update
		@siswa = Siswa.find(params[:id])
		if 
			@siswa.update(resource_params)
			flash[:notice] = 'Data siswa baru atas nama ' +@siswa.nama+ ' berhasil diperbaharui'
			redirect_to siswa_path(@siswa)
		else
			render 'new'
		end
	end

	def destroy
		@siswa = Siswa.find(params[:id])
		@siswa.destroy
		flash[:notice] = 'Data siswa baru atas nama ' +@siswa.nama+ ' berhasil dihapus'
		redirect_to siswas_path()
	end


	def import
		Siswa.import(params[:file])
		redirect_to root_url, notice: 'Siswa berhasil diimport'
	end


	private

	def resource_params
		params.require(:siswa).permit(:nama, :jenis_kelamin, :nisn, :tempat_lahir, :tanggal_lahir, :sekolah_asal, :no_un, :nama_ortu, :no_hp)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
		case level
			when 'notice' then "alert alert-info"
			when 'success' then "alert alert-success"
			when 'danger' then "alert alert-danger"
			when 'warning' then "alert alert-warning"
		end
	end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Daftar Ulang Siswa Baru', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= user_signed_in? ? current_user.name : 'Hai Guest' %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <% if user_signed_in? %>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <!-- <li><%= link_to 'Daftar', new_user_registration_path %></li> -->
              <% else %>
                <li><%= link_to 'Login', new_user_session_path %></li>
              <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daftar Ulang Siswa Baru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/siswas/_form.html.erb
<%= bootstrap_form_for(@siswa, label_errors: true, inline_errors: true, layout: :horizontal) do |form| %>
	<%= form.text_field :no_un, placeholder: "No. Pendaftaran", label: "No. Pendaftaran" %>
	<%= form.text_field :nisn, placeholder: "Nomor Induk Siswa Nasional", label: "NISN" %>
	<%= form.text_field :nama, placeholder: "Nama Lengkap Siswa", label: "Nama Siswa" %>
	<%= form.select :jenis_kelamin, [['Perempuan', 'P'], ['Laki-laki', 'L']], prompt: "Pilih Jenis Kelamin", label: "Jenis Kelamin" %>
	<%= form.text_field :tempat_lahir, placeholder: "Tempat Lahir", label: "Tempat Lahir" %>
	<%= form.date_select :tanggal_lahir, :start_year => 2000, :order => [:day, :month, :year], include_blank: true %>
	<%= form.text_field :sekolah_asal, placeholder: "Sekolah Asal", label: "Sekolah Asal" %>
	<%= form.text_field :nama_ortu, placeholder: "Nama Orangtua", label: "Nama Orangtua" %>
	<%= form.text_field :no_hp, placeholder: "Nomor HP", label: "Nomor HP" %>
	<%= form.submit 'Simpan', class: 'btn btn-primary' %> | 
	<%= link_to 'Kembali', siswas_path, class: 'btn btn-primary' %>
<% end %>

app/views/siswas/edit.html.erb
<div class="row">
	<div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Edit Data Siswa</h2>
            </div>

            <div class="panel-body">
    			<%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/siswas/index.html.erb
<div class="row">
	<div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Data Siswa</h2>
            </div>
            <div class="panel-body">
                <% if user_signed_in? %>
                <div class="alert alert-info">
                    <b>Jumlah siswa yang telah daftar ulang : </b>
                    <table>
                        <thead>
                            <tr>
                                <th>Laki-laki</th>
                                <th> : </th>
                                <th><%= Siswa.total_laki %> siswa</th>
                            </tr>
                            <tr>
                                <th>Perempuan &nbsp;</th>
                                <th> : &nbsp;</th>
                                <th><%= Siswa.total_perempuan %> siswa</th>
                            </tr>
                            <tr>
                                <th>Jumlah</th>
                                <th> : </th>
                                <th><%= Siswa.total_jenis_kelamin %> siswa</th>
                            </tr>
                        </thead>
                    </table>
                </div>
                <hr>
                <% end %>
                <%= content_tag :table, role: :datatable, data: { url: siswas_path(format: :json)} do %>
                    <thead>
                        <tr>
                            <th>No. Pendaftaran</th>
                            <th>NISN</th>
                            <th>Nama Siswa</th>
                            <th>JK</th>
                            <th>Tempat Lahir</th>
                            <th>Tanggal Lahir</th>
                            <% if user_signed_in? %>
                                <th></th>
                            <% end %>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                <% end %>
                <hr>
                <% if user_signed_in? %>
                    <%= form_tag import_siswas_path, multipart: true, class: 'form-inline' do %>

                      <div class="form-group">
                        <%= link_to "Export Data Siswa ke CSV", siswas_path(format: "csv"), class: 'btn btn-primary' %>
                      </div>
                      <div class="form-group">
                        <%= file_field_tag :file, class: '' %>
                      </div>
                      
                      <div class="form-group">
                        <%= submit_tag "Import Data Siswa", class: 'btn btn-info' %>
                      </div>

                      <div class="form-group">
                        <%= link_to 'Tambah Data Siswa Baru', new_siswa_path, class: 'btn btn-primary' %>
                      </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/siswas/new.html.erb
<div class="row">
	<div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Tambah Data Siswa Baru</h2>
            </div>

            <div class="panel-body">
    			<%= render 'form' %>
            </div>
        </div>
    </div>
</div>

app/views/siswas/show.html.erb
<div class="row">
	<div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Detail Data Siswa</h2>
            </div>

            <div class="panel-body">
                <table class="table">
                    <tr>
                        <th>No. Pendaftaran</th>
                        <td>:</td>
                        <td>
                            <%= @siswa.no_un %>
                        </td>
                    </tr>                    
                    <tr>
                        <th>NISN</th>
                        <td>:</td>
                        <td>
                            <%= @siswa.nisn %>
                        </td>
                    </tr>                    
                    <tr>
                        <th>Nama</th>
                        <td>:</td>
                        <td>
                            <%= @siswa.nama %>
                        </td>
                    </tr>
                    <tr>
                        <th>Jenis Kelamin</th>
                        <td>:</td>
                        <td>
                            <%= @siswa.jenis_kelamin %>
                        </td>
                    </tr>

                    <tr>
                        <th>Tempat Lahir</th>
                        <td>:</td>
                        <td>
                            <%= @siswa.tempat_lahir %>
                        </td>
                    </tr>
                    <tr>
                        <th>Tanggal Lahir</th>
                        <td>:</td>
                        <td>
                            <%= I18n.l(@siswa.tanggal_lahir) %>
                        </td>
                    </tr>
                    <tr>
                        <th>Sekolah Asal</th>
                        <td>:</td>
                        <td>
                            <%= @siswa.sekolah_asal %>
                        </td>
                    </tr>

                    <tr>
                        <th>Nama Orangtua</th>
                        <td>:</td>
                        <td>
                            <%= @siswa.nama_ortu %>
                        </td>
                    </tr>
                    <tr>
                        <th>No. HP</th>
                        <td>:</td>
                        <td>
                            <%= @siswa.no_hp %>
                        </td>
                    </tr>
                </table>
                <p>
                    <%= link_to "Cetak", siswa_path(@siswa, format: 'pdf'), class: 'btn btn-primary', target: :_blank %> | 
                    <%= link_to "Edit", edit_siswa_path(@siswa), class: 'btn btn-primary' %> | 
                    <%= link_to 'Kembali', siswas_path, class: 'btn btn-primary' %>
                </p>

            </div>
        </div>
    </div>
</div>